"use client";

import { useEffect, useRef, useState } from "react";

type Lang="en"|"ru"|"kz";
const words={
 en:{title:"Live camera",lead:"The image stays on this device. Access starts only after your permission.",allow:"Allow camera",stop:"Stop camera",select:"Camera source",idle:"Camera permission has not been requested",live:"LIVE",denied:"Camera access was denied. Allow it in browser site settings and try again.",missing:"No camera was found on this device.",unsupported:"This browser cannot access the camera.",bleTitle:"Bluetooth device",bleLead:"Pair a BLE camera controller or sensor for status and commands. Video is not transferred over Bluetooth.",scan:"Scan and connect",disconnect:"Disconnect",notSupported:"Web Bluetooth is unavailable. Use Chrome or Edge on Android, Windows, macOS or ChromeOS.",connected:"Connected",connecting:"Connecting…",battery:"Battery",localNote:"Live preview is real. Object detections below remain simulated until a YOLO inference endpoint is connected."},
 ru:{title:"Живая камера",lead:"Изображение остаётся на этом устройстве. Доступ включается только после вашего разрешения.",allow:"Разрешить камеру",stop:"Остановить камеру",select:"Источник камеры",idle:"Разрешение на камеру ещё не запрашивалось",live:"В ЭФИРЕ",denied:"Доступ к камере запрещён. Разрешите его в настройках сайта браузера и повторите попытку.",missing:"На этом устройстве камера не найдена.",unsupported:"Этот браузер не поддерживает доступ к камере.",bleTitle:"Bluetooth-устройство",bleLead:"Подключите BLE-контроллер камеры или сенсор для статуса и команд. Видео через Bluetooth не передаётся.",scan:"Найти и подключить",disconnect:"Отключить",notSupported:"Web Bluetooth недоступен. Используйте Chrome или Edge на Android, Windows, macOS или ChromeOS.",connected:"Подключено",connecting:"Подключение…",battery:"Заряд",localNote:"Живое изображение настоящее. Детекции объектов ниже остаются тестовыми, пока не подключён сервер YOLO."},
 kz:{title:"Тікелей камера",lead:"Кескін осы құрылғыда қалады. Қолжетімділік тек сіздің рұқсатыңыздан кейін қосылады.",allow:"Камераға рұқсат беру",stop:"Камераны тоқтату",select:"Камера көзі",idle:"Камера рұқсаты әлі сұралмады",live:"ТІКЕЛЕЙ",denied:"Камераға рұқсат берілмеді. Браузердегі сайт баптауларынан рұқсат беріп, қайталап көріңіз.",missing:"Бұл құрылғыда камера табылмады.",unsupported:"Бұл браузер камераға қолжетімділікті қолдамайды.",bleTitle:"Bluetooth құрылғысы",bleLead:"Күй мен командалар үшін BLE камера контроллерін немесе сенсорды қосыңыз. Видео Bluetooth арқылы берілмейді.",scan:"Табу және қосу",disconnect:"Ажырату",notSupported:"Web Bluetooth қолжетімсіз. Android, Windows, macOS немесе ChromeOS-та Chrome не Edge қолданыңыз.",connected:"Қосылды",connecting:"Қосылуда…",battery:"Қуат",localNote:"Тікелей көрініс нақты. YOLO сервері қосылғанша төмендегі объект анықтаулары сынақ режимінде қалады."}
} as const;

export function LiveCameraPanel({lang}:{lang:Lang}){
 const t=words[lang],videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),bleRef=useRef<any>(null);
 const[status,setStatus]=useState<"idle"|"requesting"|"live"|"error">("idle"),[error,setError]=useState(""),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[deviceId,setDeviceId]=useState(""),[bleStatus,setBleStatus]=useState<"idle"|"connecting"|"connected"|"error">("idle"),[bleName,setBleName]=useState(""),[battery,setBattery]=useState<number|null>(null);
 const bluetoothSupported=typeof navigator!=="undefined"&&Boolean((navigator as any).bluetooth);
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(track=>track.stop());try{bleRef.current?.gatt?.disconnect()}catch{}},[]);
 const stopCamera=()=>{streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setStatus("idle")};
 const startCamera=async(selectedId?:string)=>{setError("");if(!navigator.mediaDevices?.getUserMedia){setStatus("error");setError(t.unsupported);return}setStatus("requesting");streamRef.current?.getTracks().forEach(track=>track.stop());try{const requested=selectedId?{deviceId:{exact:selectedId}}:{width:{ideal:1280},height:{ideal:720}};let stream:MediaStream;try{stream=await navigator.mediaDevices.getUserMedia({video:requested,audio:false})}catch(firstError){if(firstError instanceof DOMException&&firstError.name==="OverconstrainedError")stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});else throw firstError}streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;void videoRef.current.play().catch(()=>undefined)}const list=await navigator.mediaDevices.enumerateDevices();const cameras=list.filter(item=>item.kind==="videoinput");setDevices(cameras);const activeId=stream.getVideoTracks()[0]?.getSettings().deviceId||selectedId||"";setDeviceId(activeId);setStatus("live")}catch(err){setStatus("error");const name=err instanceof DOMException?err.name:"";setError(name==="NotAllowedError"||name==="SecurityError"?t.denied:name==="NotFoundError"||name==="OverconstrainedError"?t.missing:(err instanceof Error?err.message:t.unsupported))}};
 const pairBluetooth=async()=>{const bluetooth=(navigator as any).bluetooth;if(!bluetooth){setBleStatus("error");return}setBleStatus("connecting");try{const device=await bluetooth.requestDevice({acceptAllDevices:true,optionalServices:["battery_service","device_information"]});bleRef.current=device;setBleName(device.name||"BLE device");device.addEventListener?.("gattserverdisconnected",()=>{setBleStatus("idle");setBattery(null)});const server=await device.gatt?.connect();setBleStatus(server?.connected?"connected":"error");try{const service=await server?.getPrimaryService("battery_service");const characteristic=await service?.getCharacteristic("battery_level");const value=await characteristic?.readValue();if(value)setBattery(value.getUint8(0))}catch{setBattery(null)}}catch(err){if(err instanceof DOMException&&err.name==="NotFoundError")setBleStatus("idle");else setBleStatus("error")}};
 const disconnectBluetooth=()=>{try{bleRef.current?.gatt?.disconnect()}catch{}bleRef.current=null;setBleStatus("idle");setBleName("");setBattery(null)};
 return <section className="live-hardware-grid"><article className="panel live-camera-card"><div className="live-card-head"><div><small>CAMERA API</small><h3>{t.title}</h3><p>{t.lead}</p></div>{status==="live"&&<span className="live-badge"><i/>{t.live}</span>}</div><div className={`video-stage ${status}`}><video ref={videoRef} muted playsInline/><div className="video-placeholder"><span>◎</span><b>{status==="requesting"?"…":error||t.idle}</b></div></div><div className="hardware-controls">{status!=="live"?<button className="primary big" onClick={()=>startCamera()} disabled={status==="requesting"}>{t.allow}</button>:<><label>{t.select}<select value={deviceId} onChange={event=>startCamera(event.target.value)}>{devices.map((device,index)=><option key={device.deviceId} value={device.deviceId}>{device.label||`Camera ${index+1}`}</option>)}</select></label><button className="danger-button" onClick={stopCamera}>{t.stop}</button></>}</div><div className="camera-truth">ⓘ {t.localNote}</div></article><article className="panel bluetooth-card"><div className="bluetooth-symbol">B</div><small>WEB BLUETOOTH</small><h3>{t.bleTitle}</h3><p>{t.bleLead}</p>{bleStatus==="connected"?<div className="ble-device"><span className="pulse teal"/><div><b>{bleName}</b><small>{t.connected}{battery!==null?` · ${t.battery} ${battery}%`:""}</small></div></div>:<div className={`ble-support ${bluetoothSupported?"ok":"warning"}`}>{bluetoothSupported?"● Web Bluetooth ready":t.notSupported}</div>}<div className="ble-actions">{bleStatus==="connected"?<button onClick={disconnectBluetooth}>{t.disconnect}</button>:<button className="primary big" onClick={pairBluetooth} disabled={!bluetoothSupported||bleStatus==="connecting"}>{bleStatus==="connecting"?t.connecting:t.scan}</button>}</div>{bleStatus==="error"&&<p className="hardware-error">{t.notSupported}</p>}</article></section>
}
